name: Tests

on:
  push:
    branches: 
      - develop
  pull_request:
    branches: 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install packages
        run: make install
      - name: Check format
        run: make check
      - name: Check tests
        run: make tests